name: Install and test RE
on: 
  push

jobs:
  test:
    strategy:
        matrix:
#            r-os: [r3.6.3-centos7, r4.1.0-centos7]
            r-os: [r3.6.3-centos7]
    runs-on: ubuntu-latest
    steps:
#      - name: fix docker bug
#        run: |
#          export DOCKER_BUILDKIT=0
#          export COMPOSE_DOCKER_CLI_BUILD=0
      - name: tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF##*/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Docker Version
        run: docker --version
    - name: Install Latest Docker
        run: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
            sudo apt-get update
            sudo apt-get install docker-ce
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: .github/workflows/Dockerfile-${{ matrix.r-os }}
#          tags: docker.pkg.github.com/yuri05/hello-github-actions/base-${{ matrix.r-os }}:${{ steps.tag_name.outputs.SOURCE_TAG}}
#          load: true
